/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sinbad.thrift.demo;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class HelloWorldServiceConstants {

  public static final int SERVICE_PORT = 8089;

}
